name: black

on: [push,pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - name: get_files
        run: |
          echo ::set-env name=CHANGED_FILES::${{ steps.file_changes.outputs.files}}
      - uses: actions/checkout@v2.3.2
      - uses: lgeiger/black-action@v1.0.1
        with:
          args: "${{ env.CHANGED_FILES }} --check"
