name: black

on: [push,pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - name: get_files
      - uses: actions/checkout@v2.3.2
      - uses: lgeiger/black-action@v1.0.1
        with:
          args: "${{ steps.file_changes.outputs.files}} --check"
