name: black

on: [push,pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: lgeiger/black-action@v1.0.1
      - uses: jitterbit/get-changed-files@v1
        - run: |
            for changed_file in ${{ steps.files.outputs.all }}; do
              echo "Do something with this ${changed_file}."
            done
