name: black

on: [push,pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: jitterbit/get-changed-files@v1
      - name: Get Changed Files
        run: |
          echo outputsall && echo ${{ steps.files.outputs.all }}
